// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnzZeymjmDDWx9aY6kvc1lxPKkkU4RqQw',
    appId: '1:1081079915970:web:43895e915a455ed91da25b',
    messagingSenderId: '1081079915970',
    projectId: 'flutter-auth-25b71',
    authDomain: 'flutter-auth-25b71.firebaseapp.com',
    storageBucket: 'flutter-auth-25b71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBObvFExsvmurP7bCzl4-YlnRr7U0xQXAI',
    appId: '1:1081079915970:android:e18faba6d98c43eb1da25b',
    messagingSenderId: '1081079915970',
    projectId: 'flutter-auth-25b71',
    storageBucket: 'flutter-auth-25b71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs16uT7mKXBIZ16laelTr3Yk6ZCPUuheo',
    appId: '1:1081079915970:ios:bd62519bc57b21a01da25b',
    messagingSenderId: '1081079915970',
    projectId: 'flutter-auth-25b71',
    storageBucket: 'flutter-auth-25b71.appspot.com',
    iosClientId: '1081079915970-2mg2kmj50tikn7j9cga7v8lvfmab96d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs16uT7mKXBIZ16laelTr3Yk6ZCPUuheo',
    appId: '1:1081079915970:ios:2d109a9caf3e25cb1da25b',
    messagingSenderId: '1081079915970',
    projectId: 'flutter-auth-25b71',
    storageBucket: 'flutter-auth-25b71.appspot.com',
    iosClientId: '1081079915970-7f15pb980irde60v5qf5btaf21dlmsnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth.RunnerTests',
  );
}
